trigger:
  batch: true

variables:
- template: pipelines/variables.yml

resources:
  repositories:
  - repository: configuration
    name: unify-configs
    type: git
    ref: master

stages:
- stage: SonarCloudScan
  jobs:
  - job: SonarCloudScan
    pool:
      vmImage: ubuntu-20.04
    steps:
    - task: SonarCloudPrepare@2
      displayName: Prepare for the SonarCloud analysis
      inputs:
        SonarCloud: 'services-sonar-cloud'
        organization: 'centricaengineeringservicesna'
        scannerMode: 'CLI'
        configMode: 'file'
        extraProperties: |
          sonar.pullrequest.vsts.instanceUrl=$(System.CollectionUri)
          sonar.pullrequest.vsts.project=$(System.TeamProject)
          sonar.pullrequest.vsts.repository=$(Build.Repository.Name)
          sonar.projectName=$(Build.Repository.Name)
          sonar.projectKey=$(sonarCloudProjectKey)
    - task: SonarCloudAnalyze@2
      displayName: Analyze source code with the SonarCloud
    - task: SonarCloudPublish@2
      displayName: Publish SonarCloud analysis results
      inputs:
        pollingTimeoutSec: 300

- stage: BuildQa365
  condition: and(succeeded('SonarCloudScan'), eq(variables.isQa365Branch, true))
  dependsOn:
  - SonarCloudScan
  jobs:
  - job: BuildQa365
    pool:
      vmImage: ubuntu-20.04
    steps:
    - template: pipelines/build.yml
      parameters:
        node: $(nodeVersion)
        artifact: $(qa365Artifact)
        config: $(qa365Config)

- stage: DeployQa365
  condition: and(succeeded('BuildQa365'), eq(variables.isQa365Branch, true))
  dependsOn:
  - SonarCloudScan
  - BuildQa365
  jobs:
  - deployment: DeployQa365
    pool:
      vmImage: ubuntu-20.04
    environment: homeprotection-dev
    strategy:
      runOnce:
        deploy:
          steps:
          - template: pipelines/deploy.yml
            parameters:
              region: $(awsRegion)
              credentials: $(awsCredentialsDev)
              bucket: $(qa365Bucket)
              artifact: $(qa365Artifact)
              distribution: $(qa365Distribution)

- stage: BuildDev365
  condition: and(succeeded('SonarCloudScan'), eq(variables.isDev365Branch, true))
  dependsOn:
  - SonarCloudScan
  jobs:
  - job: BuildDev365
    pool:
      vmImage: ubuntu-20.04
    steps:
    - template: pipelines/build.yml
      parameters:
        node: $(nodeVersion)
        artifact: $(dev365Artifact)
        config: $(dev365Config)

- stage: DeployDev365
  condition: and(succeeded('BuildDev365'), eq(variables.isDev365Branch, true))
  dependsOn:
  - SonarCloudScan
  - BuildDev365
  jobs:
  - deployment: DeployDev365
    pool:
      vmImage: ubuntu-20.04
    environment: homeprotection-dev
    strategy:
      runOnce:
        deploy:
          steps:
          - template: pipelines/deploy.yml
            parameters:
              region: $(awsRegion)
              credentials: $(awsCredentialsDev)
              bucket: $(dev365Bucket)
              artifact: $(dev365Artifact)
              distribution: $(dev365Distribution)

- stage: BuildQa1
  condition: and(succeeded('SonarCloudScan'), eq(variables.isQa1Branch, true))
  dependsOn:
  - SonarCloudScan
  jobs:
  - job: BuildQa1
    pool:
      vmImage: ubuntu-20.04
    steps:
    - template: pipelines/build.yml
      parameters:
        node: $(nodeVersion)
        artifact: $(qa1Artifact)
        config: $(qa1Config)

- stage: DeployQa1
  condition: and(succeeded('BuildQa1'), eq(variables.isQa1Branch, true))
  dependsOn:
  - SonarCloudScan
  - BuildQa1
  jobs:
  - deployment: DeployQa1
    pool:
      vmImage: ubuntu-20.04
    environment: homeprotection-dev
    strategy:
      runOnce:
        deploy:
          steps:
          - template: pipelines/deploy.yml
            parameters:
              region: $(awsRegion)
              credentials: $(awsCredentialsDev)
              bucket: $(qa1Bucket)
              artifact: $(qa1Artifact)
              distribution: $(qa1Distribution)

- stage: BuildHf1
  condition: and(succeeded('SonarCloudScan'), eq(variables.isHf1Branch, true))
  dependsOn:
  - SonarCloudScan
  jobs:
  - job: BuildHf1
    pool:
      vmImage: ubuntu-20.04
    steps:
    - template: pipelines/build.yml
      parameters:
        node: $(nodeVersion)
        artifact: $(hf1Artifact)
        config: $(hf1Config)

- stage: DeployHf1
  condition: and(succeeded('BuildHf1'), eq(variables.isHf1Branch, true))
  dependsOn:
  - SonarCloudScan
  - BuildHf1
  jobs:
  - deployment: DeployHf1
    pool:
      vmImage: ubuntu-20.04
    environment: homeprotection-dev
    strategy:
      runOnce:
        deploy:
          steps:
          - template: pipelines/deploy.yml
            parameters:
              region: $(awsRegion)
              credentials: $(awsCredentialsDev)
              bucket: $(hf1Bucket)
              artifact: $(hf1Artifact)
              distribution: $(hf1Distribution)

- stage: BuildDev
  condition: and(succeeded('SonarCloudScan'), eq(variables.isMasterBranch, true))
  dependsOn:
  - SonarCloudScan
  jobs:
  - job: BuildDev
    pool:
      vmImage: ubuntu-20.04
    steps:
    - template: pipelines/build.yml
      parameters:
        node: $(nodeVersion)
        artifact: $(devArtifact)
        config: $(devConfig)

- stage: DeployDev
  condition: and(succeeded('BuildDev'), eq(variables.isMasterBranch, true))
  dependsOn:
  - SonarCloudScan
  - BuildDev
  jobs:
  - deployment: DeployDev
    pool:
      vmImage: ubuntu-20.04
    environment: homeprotection-dev
    strategy:
      runOnce:
        deploy:
          steps:
          - template: pipelines/deploy.yml
            parameters:
              region: $(awsRegion)
              credentials: $(awsCredentialsDev)
              bucket: $(devBucket)
              artifact: $(devArtifact)
              distribution: $(devDistribution)

- stage: BuildStage
  condition: and(succeeded('SonarCloudScan'), eq(variables.isMasterBranch, true))
  dependsOn:
  - SonarCloudScan
  jobs:
  - job: BuildStage
    pool:
      vmImage: ubuntu-20.04
    steps:
    - template: pipelines/build.yml
      parameters:
        node: $(nodeVersion)
        artifact: $(stageArtifact)
        config: $(stageConfig)

- stage: DeployStage
  condition: and(succeeded('BuildStage'), eq(variables.isMasterBranch, true))
  dependsOn:
  - SonarCloudScan
  - DeployDev
  - BuildStage
  jobs:
  - deployment: DeployStage
    pool:
      vmImage: ubuntu-20.04
    environment: homeprotection-stage
    strategy:
      runOnce:
        deploy:
          steps:
          - template: pipelines/deploy.yml
            parameters:
              region: $(awsRegion)
              credentials: $(awsCredentialsStage)
              bucket: $(stageBucket)
              artifact: $(stageArtifact)
              distribution: $(stageDistribution)

- stage: BuildProd
  condition: and(succeeded('SonarCloudScan'), eq(variables.isMasterBranch, true))
  dependsOn:
  - SonarCloudScan
  jobs:
  - job: BuildProd
    pool:
      vmImage: ubuntu-20.04
    steps:
    - template: pipelines/build.yml
      parameters:
        node: $(nodeVersion)
        artifact: $(prodArtifact)
        config: $(prodConfig)

- stage: DeployProd
  condition: and(succeeded('BuildProd'), eq(variables.isMasterBranch, true))
  dependsOn:
  - SonarCloudScan
  - DeployStage
  - BuildProd
  jobs:
  - deployment: DeployProd
    pool:
      vmImage: ubuntu-20.04
    environment: homeprotection-prod
    strategy:
      runOnce:
        deploy:
          steps:
          - template: pipelines/deploy.yml
            parameters:
              region: $(awsRegion)
              credentials: $(awsCredentialsProd)
              bucket: $(prodBucket)
              artifact: $(prodArtifact)
              distribution: $(prodDistribution)
