map $sent_http_content_type $expires {
    default                    off;
    text/html                  epoch;
    text/css                   max;
    application/javascript     max;
    application/woff2          max;
    ~image/                    30d;
}

server {
    listen       8080;
    server_name  localhost;

    gzip on;
    gzip_types text/plain text/javascript application/xml application/javascript;
    gzip_proxied    no-cache no-store private expired auth;
    gzip_min_length 100;

    add_header 'Content-Security-Policy' "frame-ancestors 'none'";
    add_header 'X-Frame-Options' 'DENY';

    expires $expires;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    error_page  400 403 404 500 502 503 504 =200 /index.html;
}
