export enum LocalStorageEnum {
  AccountNumber = 'accountNumber',
  Email = 'email',
  TaxId = 'taxId',
  CompanyName = 'companyName',
  CompanyInfo = 'companyInfo',
  PhoneNumber = 'phoneNumber',
  VendorID = 'vendorId',
  PartyName = 'partyName',
  Token = 'token',
  UserName = 'userName',
  Password = 'password',
  BusinessAddress1 = 'businessAddress1',
  BusinessAddress2 = 'businessAddress2',
  BusinessUnit = 'businessUnit',
  BusinessPostalCode = 'businesspostalCode',
  BusinessCountry = 'businessCountry',
  BusinessCity = 'businessCity',
  BusinessState = 'businessState',
  BusinessFasLocationId = 'businessFsaLocationId',
  BuisnessAddressPurpose = 'buisnessAddressPurpose',
  BusinessAxLocationId = 'businessAxLocationId',
  BusinessAxRecordId = 'businessAxRecordId',
  MailingAddress1 = 'mailingAddress1',
  MailingAddress2 = 'mailingAddress2',
  MailingUnit = 'mailingUnit',
  MailingPostalCode = 'mailingpostalCode',
  MailingCity = 'mailingCity',
  MailingState = 'mailingState',
  MailingFasLocationId = 'mailingFsaLocationId',
  MailingCountry = 'mailingCountry',
  MailingAddressPurpose = 'mailingAddressPurpose',
  MailingAxLocationId = 'businessAxLocationId',
  MailingAxRecordId = 'businessAxRecordId',
  
}
