export enum LocalStorageEnum {
  AccountNumber = 'accountNumber',
  Email = 'email',
  TaxId = 'taxId',
  CompanyName = 'companyName',
  PhoneNumber = 'phoneNumber',
  Address1 = 'address1',
  Address2 = 'address2',
  Unit = 'unit',
  PostalCode = 'postalCode',
  City = 'city',
  State = 'state',
  VendorID = 'vendorId',
  FasLocationId = 'fsaLocationId',
  PartyName = 'partyName',
  Country = 'country',
  Token = 'token',
  UserName = 'userName',
  Password = 'password'
}
